<setting>
    <tag load="mofron-comp-appbase">AppBase</tag>
    <tag load="mofron-comp-text">Text</tag>
    <tag load="mofron-comp-image">Image</tag>
    <!-- effect -->
    <tag load="mofron-effect-hrzpos">HrzPos</tag>
    <!-- event -->
    <tag load="mofron-event-clicktap">ClickTap</tag>
    <access-style>
        <mobile orientation=portrait>font-size:625%;</mobile>
        <mobile orientation=landscape>font-size:800%;</mobile>
        <tablet>font-size:800%;</tablet>
        <default>font-size:625%;</default>
    </access-style>
</setting>

<script src="./mof/js/Thermo.js" run=after></script>
<script run=after>
let thm_prs = () => {
    try {
        let thd_txt = dropd.text()[dropd.select()].text();
        let thd_val = parseFloat(thd_txt.substring(0, thd_txt.length-1));
        let thermo  = new Thermo(thd_val);
        
        /* websocket connection callback */
        thermo.wsk_callback((ws_p) => {
            (true === ws_p) ? moni.start() : moni.stop();
        });
        
        /* thermo info receive event */
        thermo.inf_event((msg) => {
            try {
                act.base64("data:image/bmp;base64," + msg.image);
                temp_val.text(msg.temperature + "");
            } catch (e) {
                console.error(e.stack);
                throw e;
            }
        });
        
        /* thermo status change event */
        thermo.sts_event((sts) => {
            if ("none" === sts) {
                rslt.none();
            } else if ("pass") {
                rslt.pass();
            } else {
                rslt.alert();
            }
            //console.log(sts);
        });
        
        thermo.start();
    } catch (e) {
        console.error(e.stack);
        throw e;
    }
}
setTimeout(thm_prs,500);
</script>


<script name=bar_evt run=init>
menu_cmp.visible(true);
</script>

<AppBase title="SeekGate" main-color=[230,255,230]>
    <theme>
        <Text font="Cairo" main-color=[96,131,127]></Text>
    </theme>
    <style>overflow:hidden;</style>
    
    <header:pull>
        <navi>
            <Image size=(0.3rem,0.3rem) event=ClickTap:@bar_evt>./img/bars.png</Image>
        </navi>
    </header:pull>
    
    <div>
        <!-- slides from the right side when bar-text was tapped -->
        <mf:load name=menu>./mof/slidemenu.mof</mf:load>
        <!-- display the status of thermo camera -->
        <mf:load name=moni>./mof/monitor.mof</mf:load>
        <!-- temperature -->
        <mf:load name=temp>./mof/temperature.mof</mf:load>
        <!-- check result -->
        <mf:load name=rslt>./mof/result.mof</mf:load>
    </div>
</AppBase>
