<setting>
    <tag load="mofron-comp-appbase">AppBase</tag>
    <tag load="mofron-comp-text">Text</tag>
    <!-- effect -->
    <tag load="mofron-effect-hrzpos">HrzPos</tag>
    <!-- event -->
    <tag load="mofron-event-click">Click</tag>
    <access-style>
        <mobile orientation=portrait>font-size:1500%;</mobile>
        <mobile orientation=landscape>font-size:800%;</mobile>
        <tablet>font-size:800%;</tablet>
        <default>font-size:625%;</default>
    </access-style>
</setting>

<script src="./mof/js/Thermo.js" run=init></script>
<script run=init>
let thermo = new Thermo([moni, temp, swch]);
let sw_evt = () => {
    try {
        thermo.switching(!thermo.status());
    } catch (e) {
        console.error(e.stack);
    }
}
</script>


<script name=bar_evt run=init>
menu_cmp.visible(true);
</script>

<AppBase title="SeekGate" main-color=[230,255,230]>
    <theme>
        <Text font="serif"></Text>
    </theme>
    
    <header:navi>
        <Text size=0.4rem event=Click:@bar_evt>&equiv;</Text>
    </header:navi>
    
    <!-- slides from the right side when bar-text was tapped -->
    <mf:load name=menu>./mof/slidemenu.mof</mf:load>
    
    <!-- display the status of thermo camera -->
    <mf:load name=moni>./mof/monitor.mof</mf:load>
    
    <!-- temperature -->
    <mf:load name=temp>./mof/temperature.mof</mf:load>
    
    <!-- switching the thermal camera on/off when the circle is tapped -->
    <mf:load name=swch>./mof/switch.mof<mf:load>
</AppBase>
