<setting>
    <tag load="mofron-comp-circle">Circle</tag>
    <tag load="mofron-effect-color">Color</tag>
</setting>

<script name=start run=external>
swcir.execEffect(2);
dsc_txt.visible(false);
</script>

<script name=stop run=external>
swcir.execEffect(3);
dsc_txt.visible(true);
</script>

<div style="position:fixed;bottom:0.1rem;" effect=HrzPos>
    <Circle name=swcir size=0.8rem base-color=[250,80,80] event=Click:@sw_evt>
        <effect>
            <HrzPos></HrzPos>
            <Color eid=2 speed=500>[80,80,250]</Color>
            <Color eid=3 speed=500>[250,80,80]</Color>
        </effect>
        <Image size=(0.6rem,0.6rem) src="./img/switch.png">
            <effect>
                <HrzPos></HrzPos>
                <VrtPos></VrtPos>
            </effect>
        </Image>
    </Circle>
    <div height=0.5rem, width=100%>
        <Text name=dsc_txt size=0.3rem effect=HrzPos>Tap to Start</Text>
    </div>
</div>
